### ISSUE TITLE
cross-realm?

### ISSUE THREAD

**Issue by getify** [w3c/preload#12] opened 2015-03-10 22:46 UTC
If I "preload" a resource in a parent page then make the "matching" request in an iframe, or otherwise in some other realm (web workers, etc), does it all match up? Or is this only per realm?

**Comment by igrigorik** [comment] 2015-03-10 22:53
Subject to regular HTTP caching semantics -- max-age, etc. For resources that are "no-cache" the resource is only retained within that navigation context. 

Once again, dupe of https://github.com/w3c/resource-hints/issues/2 - let's continue there.

**Closed as completed by igrigorik** 2015-03-10 22:53 UTC
