### ISSUE TITLE
Should the spec say something about the `request destination` of an HTTP/2 push?

### ISSUE THREAD

**Issue by deweerdt** [w3c/preload#94] opened 2017-05-18 15:22 UTC
It is my understanding that when a resource is pushed, the browser infers the request destination from the content-type (but I couldn't quite figure out how the mapping is done from https://fetch.spec.whatwg.org/). So presumably, if we push `/style.css` with a `text/css` content-type it will be assigned a `style` request destination.

If a request arrives after that push with a `link: </style.css>; rel=preload` header, since the `request destination` is effectively an empty string, this could cause the browser to fetch the resource again.

Should "2.3 Server Push (HTTP/2)" say something about that mapping from content-type to request destination?

**Comment by igrigorik** [comment] 2017-05-18 15:44
> It is my understanding that when a resource is pushed, the browser infers the request destination from the content-type (but I couldn't quite figure out how the mapping is done from https://fetch.spec.whatwg.org/). So presumably, if we push /style.css with a text/css content-type it will be assigned a style request destination.

No, response content-type does not determine the destination.. Which is why you can't find the mapping.

> If a request arrives after that push with a link: </style.css>; rel=preload header, since the request destination is effectively an empty string, this could cause the browser to fetch the resource again.

No, it does not. Forget about push for a second and just think of resources in the HTTP cache.. If there's a valid response in the cache for requested URL, it can be used to satisfy a request from the renderer. Before that happens, the renderer checks its policies (e.g. am I allowed to fetch this URL per CSP policy).. which is where destination is relevant.

**Comment by deweerdt** [comment] 2017-05-18 15:52
I see, thanks. I based my reasoning on the observed behavior of Chrome [which appears to re-fetch](https://github.com/h2o/h2o/issues/1303) pushed resources when the request destination is not explicitly set via the `as=` attribute in the `link:` header. I thought that this bit:

> When the as attribute of the link element of a preload link that is already in a Document is set or changed to a value that does not or no longer matches the request destination of the previous obtained external resource, if any.

explained why Chrome was fetching the resource again. What am I missing?

**Comment by igrigorik** [comment] 2017-05-18 16:50
The language is there to ensure that when a link element is mutated.. a new fetch may be needed - e.g. a different CSP policy is now in effect, or some such.

That said, there may be some implementation gotchas here on both ends (server and client). A trace and/or crbug.com/ report is probably the right place to start. /cc @yoavweiss

**Comment by yoavweiss** [comment] 2017-05-19 12:11
Chromium is double fetching these resources (at least from the renderer's perspective) because it is loading the resource once as a raw resource (empty `as` value) and once as its real destination.

I think the right answer here is https://github.com/w3c/preload/issues/80. When Link headers are just used as push instructions and have no `as` value, they should be ignored by the browser. That's not the situation today, but we should and are aiming to fix it.

**Comment by yoavweiss** [comment] 2017-05-19 12:30
Closing as a duplicate of #80

**Closed as completed** 2017-05-19 12:30 UTC
