### ISSUE TITLE
Early fetching files being preloaded as crossorigin fetch cause .json files to be downloaded twice

### ISSUE THREAD

**Issue by Media-Evil** [w3c/preload#160] opened 2021-09-21 22:36 UTC
By early preloads I mean those that occur as soon as the module containing the fetch request evaluates (browser will notify you that the resource has been preloaded, but never used even while CORS credentials match on both HTTP Link header of a response and on the fetch request being sent).

Delaying the fetch request for ~20ms or more (I haven't tested the upper limit) on up to date (as of 21.09.2021) Chrome fixes the problem and Chrome will stop complaining about the preload being unused. For up to date (as of 21.09.2021) Firefox, 0ms delay is enough to achieve the same effect.

I've created [a repo](https://github.com/Media-Evil/crossorigin-preload-as-fetch-glitch) where you can confirm this on your own. Or tell me that I'm doing something wrong.

**Comment by yoavweiss** [comment] 2021-09-23 09:04
I suspect that the issue is due to the fact that you're using a `use-credentials` `crossorigin` value, which doesn't match what `fetch` uses by default. 

Closing, as this is not a spec issue.

**Closed as completed by yoavweiss** 2021-09-23 09:04 UTC
