### ISSUE TITLE
matching... "out of scope"?

### ISSUE THREAD

**Issue by getify** [w3c/preload#8] opened 2015-03-10 22:10 UTC
Seems like matching is a pretty critical part of this being successful or not. Can we at least specify that matching, whatever it is, is at least done on the final canonicalized URL, such that preloads and matching requests can be different versions of relative/absolute and still be considered "matching"?

Thinking about cases like `https:// ...` vs `// ...` (protocol-independent requests) more than paths. Also, are URL parameters (typically cache-busting) considered in the matching? What about fragments in the URLs?

**Comment by igrigorik** [comment] 2015-03-10 22:30
This is a dupe of https://github.com/w3c/resource-hints/issues/2; closing this, let's continue there.

**Closed as completed by igrigorik** 2015-03-10 22:30 UTC
