### ISSUE TITLE
Urgency hints

### ISSUE THREAD

**Issue by mnot** [w3c/preload#66] opened 2016-06-03 01:23 UTC
Right now, when I use `preload` to hint H2 server push, the implementation I'm using (mod_h2) will push those responses after the main HTML's body.

In some cases, however, these resources are blocking render. To get full parity with inline content, pushed content needs to be available before the rest of the HTML.

There are a lot of ways this could be hinted, but I think it should be kept relatively simply. My suggestion is to define two new parameters on the link relation:
- `critical` - this resource needs to be pushed in its entirety before the "parent" response is complete; ideally, within the first ~1k of it.
- `critical-head` - the first ~512 bytes of this resource need to be pushed before the "parent" response is complete; ideally, within the first ~1k of it. The remaining content can come afterwards.

E.g.,

```
Link: </style-crit.css>; rel="preload"; critical
Link: </images/foo.jpg>; rel="preload"; critical-head
```

There are a lot of different ways to specify this (e.g., using different link relations; using a single parameter with multiple values), of course.

**Comment by mnot** [comment] 2016-06-03 01:24
Ping @kazuho @icing

**Comment by kazuho** [comment] 2016-06-03 01:46
FWIW, both mod_h2 and H2O prioritizes pushed streams depending on their content-type header.

mod_h2 has a configuration directive called [H2PushPriority](https://icing.github.io/mod_h2/push.html#h2pushpriority) for the purpose, that takes three options as arguments: after, before, interleaved.  The pushed streams are prioritized accordingly.

H2O prioritizes the pushed streams by referring to the `priority` attribute of the MIME mapping (see [file.mime.addtypes](https://h2o.examp1e.net/configure/file_directives.html#file.mime.addtypes)).  If set to true, the pushed stream is sent before the stream that triggered the push (i.e. has the same effect as `before` of mod_h2).  Otherwise, the pushed stream is prioritized as defined by the HTTP/2 specification (so it would be the same as `after` of mod_h2).

If we are to introduce a hint in the link header, it might be wise to have it defined following the models we already have.

**Comment by mnot** [comment] 2016-06-03 01:54
We don't have to worry about media types since it's per-link.

WRT the granularity of directives, I'm all for aligning with what the implementations do, _if_ it's what we need :)

`before` seems to roughly map to `critical`, with some small differences in semantics; you could certainly implement `critical` by sending it before.

Based on lots of discussions, I suspect that being able to push the first `n` bytes of a response and then hold the rest until later will be valuable. Data would be good here.

`weight` / `priority` is something that's probably separable from this. That's not to say it's unimportant, just that the goal here is to be able to closely approximate the performance properties of inlining critical content, so that people don't feel the need to fall back to it.

**Comment by kazuho** [comment] 2016-06-03 05:40
> Based on lots of discussions, I suspect that being able to push the first n bytes of a response and then hold the rest until later will be valuable.

Agreed.  My understanding is that the intention behind is to push the metadata stored in the first bytes of the resource.  Considering the fact, it would be great if the feature could be specified as _push the metatadata at the head_, instead of defining some fixed number of bytes.  That way, implementations can determine the exact number of bytes to push immediately by the value of the content-type header or by inspecting the content.

> weight / priority is something that's probably separable from this.

Agreed.  We basically need critical, critical-head, and non-critical.  It might make sense to define non-critical as a parameter as well, while leaving the default behavior as-is for the servers (i.e. use content-type).

**Comment by icing** [comment] 2016-06-03 08:26
I agree to all of this. I would prefer a name for this that better reflects the intention. Something like `inline`or `inline=512`.

The `mod_h2` priority push handling needs some make-over. As @kazuho discussed in other threads already, some things cannot wait for main response headers and need to be pushed right away, for example.

The mod_h2 way of doing pushes is currently solely triggered by response headers _and_ it schedules pushes like other requests, manipulating priorities and weight to make nghttp2 schedule it as desired. That does not always work as needed, as you noticed.

**Comment by igrigorik** [comment] 2016-06-03 17:20
> The mod_h2 priority push handling needs some make-over. As @kazuho discussed in other threads already, some things cannot wait for main response headers and need to be pushed right away, for example.

This seems orthogonal to the discussion above, correct? As in, it sounds like there is a desire for some other "out of band" mechanism that defines what resources should be pushed and when -- something like https://github.com/GoogleChrome/http2-push-manifest?

**Comment by mnot** [comment] 2016-06-04 02:53
I think maybe this should just focus on `critical` semantics for now. 

`critical-head` is interesting, but I suspect it won't be appropriate to make it a parameter on `rel=preload`, because the semantics are very different from the "native" `preload` semantics (whole vs. head).

**Comment by pelchats** [comment] 2016-06-06 17:53
I've run into a similar need to specify in what order resources should be pushed. However, the order I wish to specify is between the pushed resources.

Suppose (my actual page DAGs are more complex) a page has a render-blocking script, followed by a CSS file, an above-the-fold image and a below-the-fold image. I would like to be able to push:
1. the script
2. the CSS
3. the ATF image
4. the BTF image

Currently, those resources get pushed with whatever priorities the downstream server (e.g. `mod_h2`) decides to use (or preloaded with the default priority for each resource type by the browser).

Given that we have HTTP2 dependencies, it seems it would be nice to be able to somehow specify them in the preload header (or some other header) for use by either a downstream server like `mod_h2` or the browser. If I understand correctly this would support both your use case and mine. This can only support relative priorities between resources on the same domain.

Granted this would certainly be more complex than the current proposal, but it seems more flexible and more cohesive with the HTTP2 standard.

Obviously this doesn't address the `critical-head` case.

**Comment by igrigorik** [comment] 2016-06-07 16:39
```
Link: </inline-thing.js>; rel="preload"; before=/
Link: </style-crit.css>; rel="preload"; before=/other.js
```

Probably a terrible idea, but just throwing it out there... :)

**Comment by tombergan** [comment] 2016-06-07 17:49
Is the idea that `/` happens-before `/inline-thing.js`? (If so, I'd rename "before" to "after".) I think that might work since it lets you build a dependence tree directly.

**Comment by kazuho** [comment] 2016-06-07 18:15
Another possible solution would be to state that the preload links marked _critical_ should be fetched in the order they appear.  I believe there is no need to interleave them.

**Comment by tombergan** [comment] 2016-06-07 19:47
LRP has two different meanings:
1. within the server, it's used to label requests to push
2. between the server and browser, it tells the browser which subresources will be needed

Using an ordered list is probably fine for (1), where the goal is to simply produce an ordered list of resources to push.

For (2), the problem is that LRP resources can contend with other (non-LRP) resources found by the browser as it scans and evaluates the page. We've noticed that LRP can actually degrade performance when this contention happens (@pelchats can say more). The root problem is that the browser has no way of knowing how LRP resources should be ordered relative to non-LRP resources.

IMO, dependency information is orthogonal to LRP, and for that reason, it should be specified separately. My dream request is to have some way to communicate a dependency graph to the browser, either in a header or directly in the HTML. The graph would cover all resources needed until the page is "loaded" (for your favorite definition of "loaded"). The entire dependence graph may not be known in advance -- think of scripts that fetch dynamic content, or third party scripts that do who-knows-what -- so the graph should have some way of specifying "holes" that represent unknown resources.

Similar arguments are made by two recent research papers: [Klotski](https://www.usenix.org/conference/nsdi15/technical-sessions/presentation/butkiewicz) and [Polaris](https://www.usenix.org/conference/nsdi16/technical-sessions/presentation/netravali).

This graph could be used in many ways:
- by the server, to decide what to push and in what order (e.g., see Klotski)
- by the server, to reprioritize requests using H2 priorities (e.g., see Klotski again)
- by the client, to prioritize fetches (e.g., see Polaris)

This goes way beyond @mnot's original request, but if we solve problems like @mnot's in isolation, I fear that we'll end up with a long list of LRP annotations that sort-of solve the underlying problem but not entirely.

Thoughts?

**Comment by kazuho** [comment] 2016-06-07 20:01
@tombergan 

> For (2), the problem is that LRP resources can contend with other (non-LRP) resources found by the browser as it scans and evaluates the page. We've noticed that LRP can actually degrade performance when this contention happens (@pelchats can say more).

Thank you for describing the issue.  Sounds interesting.

> The root problem is that the browser has no way of knowing how LRP resources should be ordered relative to non-LRP resources.

I might be wrong, but isn't the `as` attribute specified in the [preload draft](https://www.w3.org/TR/preload/) supposed to address the issue?

**Comment by mpbuettner** [comment] 2016-06-07 20:22
'as' can order a script before an image, but it can't specify the ordering between scripts found in the LRP header and scripts found on the page.

If you want a modicum of ordering, you could specify all the resources in the LRP header and trust the browser to fetch them in the listed order. But you still can't order against "hidden" resources, such as dynamic resources where the URL changes on each pageload which you can't specify in the LRP header. The catch is that if the hidden resource is really important, it is blocked behind _all_ the resources you specified in the LRP header. 

[This doc](https://docs.google.com/document/d/1bCDuq9H1ih9iNjgzyAL0gpwNFiEP4TZS-YLRp_RuMlc/edit?pref=2&pli=1) is a good primer on resource prioritization in Chromium. Note the section, "Issues with Existing Scheme" -- all resources of a particular type are not equally important.

**Comment by kazuho** [comment] 2016-06-08 01:40
@mpbuettner Thank you for your response.

> 'as' can order a script before an image, but it can't specify the ordering between scripts found in the LRP header and scripts found on the page.

Correct.

> If you want a modicum of ordering, you could specify all the resources in the LRP header and trust the browser to fetch them in the listed order. But you still can't order against "hidden" resources, such as dynamic resources where the URL changes on each pageload which you can't specify in the LRP header. The catch is that if the hidden resource is really important, it is blocked behind all the resources you specified in the LRP header. 

I disagree.  The web browser should refer to the urgency specified by the LRP header for initiating requests.  But it is free to update the priority (by sending H2 PRIORITY frame) once it observes how the resource is being used (e.g. script or link tag), much the same way it issues requests for resources not already in flight.

Note that once the browser observes how the resource is used, it can be more precise and error prone in correctly prioritizing the resources than the server administrator.

In other words, **LRP should be viewed as an optimization necessary from when the browser observes the header until it discovers how the resource is used** (or for server push 1-RTT from when the server initiates the push). The fact means that LRP does not need to be as complicated as H2 prioritization, and I believe we can create optimal ordering just with `as` and `critical` (and possibly with `critical-head`) in the long term.

I understand your frustration that the implementations we have in hand is not optimal at the moment, and have no objections to having complicated ways on the server-side to prioritize the resource loads.  Actually, I do maintain a server-driven prioritization logic myself (see https://h2o.examp1e.net/configure/http2_directives.html#http2-reprioritize-blocking-assets). However, as stated, I see them as temporary workarounds, and believe that the issue would be (or should be) eventually solved by browser implementations.

> [This doc](https://docs.google.com/document/d/1bCDuq9H1ih9iNjgzyAL0gpwNFiEP4TZS-YLRp_RuMlc/edit?pref=2&pli=1) is a good primer on resource prioritization in Chromium. Note the section, "Issues with Existing Scheme" -- all resources of a particular type are not equally important.

Thank you for the link.  I believe I'm fairly familiar about resource prioritization in general and how it is done in Chrome. It might be worth noting that a new prioritization algorithm for HTTP/2 has landed into Chromium (see https://codereview.chromium.org/1733383002/, https://bugs.chromium.org/p/chromium/issues/detail?id=590225).

**Comment by tombergan** [comment] 2016-06-08 15:21
@kazuho and @igrigorik, it sounds like there is a long-term vision for LRP that I don't fully understand yet. Could you help clarify?

Part of my confusion is that LRP is being used for both push (server-side) and preload (client-side). Push and preload are different optimizations with different trade-offs. In reading this thread, I have trouble following which ideas are important for push specifically vs push and preload generally. I would hate to clutter a client-facing header with options and parameters that are only useful at the server. For this reason I think it is cleaner to separate push and preload entirely. Certainly, the WWW Consortium doesn't need to specify the protocol by which backend servers tell Apache/nginx/H2O which resources should be pushed. IMO that protocol should be an implementation detail of Apache/nginx/H2O.

Now let's focus on client-side LRP. How should I (the web developer) use this header? What are the best practices? Abstractly, the browser renders my web page by evaluating a dependency graph. Each node in this graph is a resource that must be fetched. Much of the graph is linear (e.g., synchronous scripts in `<head>`). Some resources are named directly in the HTML. These are discovered easily by the preload scanner. Other resources are _hidden_. For example, if one script loads another, the loaded script is hidden as it cannot be discovered until the first script is evaluated.

I don't think it makes sense to LRP any resource that is easily discovered by the preload scanner [1,2]. If the preload scanner can find a resource, then including it in LRP is redundant. This means LRP should be used to declare _hidden_ resources to the browser. Now comes my dilemma. My page has a number of hidden resources and I decide to LRP them. The browser _cannot_ know how to optimally fetch those hidden resources relative to other resources found by the preload scanner. It does not have enough information. (At least, I don't think it does.)

For example, suppose I need five scripts to render a page, where scripts S3 and S5 are hidden, and the URL for S3 is determined dynamically by S2. I can LRP S5, but when will the browser schedule that fetch? If the browser schedules that fetch too early, it steals bandwidth from S1 and S2 (and note that we don't even learn about S3 until S2 has executed, making it even more important to fetch S2 as quickly as possible).

This ordering problem cannot be solved by the "as" attribute. I don't see how "critical" helps either. It sounds like @kazuho wants to (partially?) solve this problem through reprioritization at the server, similarly to [Klotski](https://www.usenix.org/conference/nsdi15/technical-sessions/presentation/butkiewicz), but that requires H2 and a smart server. I don't think LRP should require a reprioritizing H2 server to perform well, and further, LRP works across domains while H2 does not. The ordering problem is maybe solvable by @igrigorik's suggestion to encode dependencies in LRP, though that still leaves the browser blind to the existence of S2 -- making the network scheduler aware of hidden, dynamic resources like S2 is one of the important features of [Polaris](https://www.usenix.org/conference/nsdi16/technical-sessions/presentation/netravali) (or so the authors claim).

Sorry for the long comment. I appreciate the discussion!

footnotes:

[1] Of course, I don't know exactly how the preload scanner works, as it can vary from browser-to-browser and even across different versions of the same browser. But the high-level idea is straight-forward, so let's say it's easy to guess how the preload scanner will work most of the time.

[2] This is another difference between push and preload. Although it does not make sense to LRP resources that are easily discovered by the preload scanner, it does make sense to push them.

**Comment by yoavweiss** [comment] 2016-06-09 11:52
@tombergan - Thank you for your comment. It very eloquently summarized the issues that I've encountered myself with current LRP, and the reason that I think push and preload semantics are distinct enough to merit their own separate `rel` values.

One more point worth emphasizing regarding your example (with slight changes, let's assume that S5 has less significance than S1 and S2, e.g. not render-blocking, but still required to display important parts of the page): 
You want to preload S5, but want to do that in a way that won't contend with S1 and S2. But since S5 is included in a header, there's a very good chance that it would get discovered earlier than S1 and S2, and since they're all scripts, S5 has a good chance of being the first resource in line.

@kazuho:

> I disagree. The web browser should refer to the urgency specified by the LRP header for initiating requests. But it is free to update the priority (by sending H2 PRIORITY frame) once it observes how the resource is being used (e.g. script or link tag), much the same way it issues requests for resources not already in flight.

Downgrading the priority is racy by definition, but even if we ignore that, it's not very helpful in the 3rd party scenario, which is a major use-case for preload (but not push). 

All in all, I believe there is value in being able to downgrade/upgrade the place in the "queue" that certain preloaded resources would have. The `before`/`after` proposal slightly scares me from an implementor's perspective, as I'm not sure how they'd be implemented without restoring the sending queue, and adding some delay to make sure all resources are discovered before they are ordered and sent to the server (which is obviously an awful solution to current issues).

**Comment by igrigorik** [comment] 2016-07-23 00:28
After re-reading this once over, I think we might want to separate the "I want to communicate a full dependency graph use case" from the original problem presented by Mark:

> Right now, when I use preload to hint H2 server push, the implementation I'm using (mod_h2) will push those responses after the main HTML's body. In some cases, however, these resources are blocking render. To get full parity with inline content, pushed content needs to be available before the rest of the HTML.

The above use case is crisp and relevant to many sites. For example, PageSpeed recommends that sites inline critical CSS to enable 1RTT render, but doing so means you duplicate your critical CSS across all of your pages and it would sure be nice to be able to use h2 push to address this. 

`Link: </style-crit.css>; rel="preload"; critical`

As covered above, I think there is consensus that the above ("critical") modifier would be sufficient. Servers can use that as a signal that the resource should be pushed before and/or interleaved with the head of the parent resource.

@mnot @kazuho @icing yay/nay?

---

Resolving the larger problem of communicating the full resource graph, filling in 'holes' in the raph, etc., I think is a separate (interesting, but separate) discussion. In fact, to me this smells like a whole separate mechanism that could be used by the application to communicate the graph to override browser defaults, etc. I propose we take this part of the discussion to WICG and iterate there.

**Comment by icing** [comment] 2016-07-23 06:26
> Am 23.07.2016 um 02:29 schrieb Ilya Grigorik notifications@github.com:
> Link: </style-crit.css>; rel="preload"; critical
> 
> As covered above, I think there is consensus that the above ("critical") modifier would be sufficient. Servers can use that as a signal that the resource should be pushed before and/or interleaved with the head of the parent resource.
> 
> @mnot @kazuho @icing yay/nay?
> 
> Souns good to me.

**Comment by kazuho** [comment] 2016-07-24 19:00
@igrigorik +1, with the assumption that it is going to be defined as a _hint_ as @mnot suggested. In other words, introduction of `urgency` should not prohibit http2 servers from freely prioritizing the responses that lacks the `urgency` hint.

**Comment by igrigorik** [comment] 2016-07-24 19:56
Yep, that's what I was thinking.

**Comment by tombergan** [comment] 2016-07-25 23:06
The original thread got a bit derailed, sorry about that. However, I think the following comments from myself and @yoavweiss are relevant:

> Push and preload are different optimizations with different trade-offs. In reading this thread, I have trouble following which ideas are important for push specifically vs push and preload generally. I would hate to clutter a client-facing header with options and parameters that are only useful at the server. For this reason I think it is cleaner to separate push and preload entirely. Certainly, the WWW Consortium doesn't need to specify the protocol by which backend servers tell Apache/nginx/H2O which resources should be pushed. IMO that protocol should be an implementation detail of Apache/nginx/H2O.
> 
> ...
> This is another difference between push and preload. Although it does not make sense to LRP resources that are easily discovered by the preload scanner, it does make sense to push them.
> 
> ...
> I think push and preload semantics are distinct enough to merit their own separate rel values.

I am concerned about conflating push and preload. The "critical" annotation sounds like a reasonable thing for push, but what does it mean for preload? If there is no well-defined and useful meaning, then we end up with a collection of attributes where some apply to preload and others apply to push. That seems unfortunate. Further, any attribute relevant for push (but not preload) is really an implementation detail of the server that server that seems out-of-scope for the W3C.

WDYT?

**Comment by igrigorik** [comment] 2016-07-26 05:02
> I am concerned about conflating push and preload. The "critical" annotation sounds like a reasonable thing for push, but what does it mean for preload? 

It can be used as a signal to bump the fetch priority of the resource—e.g. I have a hero image on my site which needs to be fetched `as=image` but it should be assigned "critical" priority when request is emitted from the client, instead of UA default medium/low.

> If there is no well-defined and useful meaning, then we end up with a collection of attributes where some apply to preload and others apply to push. That seems unfortunate. Further, any attribute relevant for push (but not preload) is really an implementation detail of the server that server that seems out-of-scope for the W3C.

I agree that we need to be careful and think through the various interactions here, but I'm not (yet) convinced that we're at a point where we would benefit from separating these hints into separate relations. For one, that would lead to a lot of unnecessary duplication of same link values - e.g. if push is available do it, if not preload it. Further, I have a hunch that if you separate `push` into a separate relation.. you'll end up having to teach the client to interpret it as a preload anyway; if server didn't push it, fetch it, which takes us back to square one of this whole conversation.

**Comment by mnot** [comment] 2016-07-29 08:58
@igrigorik did discussion at the workshop change your position at all?

**Comment by igrigorik** [comment] 2016-08-01 20:48
@mnot not sure. 

We had a few good conversations around it with @yoavweiss @kazuho and @icing on this, and I think one thing we _did_ all agree on is: just because a resource is listed as a candidate for push does not mean that it should be pushed; the server should be smart(er) about what it pushes and when. By contrast, today most implementations treat rel=preload as a ~must push and we may want to revisit that -- note: the spec does say "server _may_ initiate server push". In short, we need to make servers smarter, and then the question is how...
- Support for cache digests would definitely help.
- Servers should probably experiment with some heuristics. In no particular order, some ideas:
  - Examine the content-type - e.g. perhaps images should be pushed in first RTT, but can be pushed later.
  - Examine the size of the resource; if the goal is to enable one-rtt render then we have constrained byte budget and we should push resources that fit within that budget; not pushing large resources in first RTT can be good feedback to developers to reduce size of critical resources.
  - ...
- Smarter hints from the origin / developer: it's easy to read preload+push as "preload and push all the things", which is what we've see in a few cases now. We probably need to do some modeling + case studies + writeup best practices for how to use these hints (e.g. don't push _all_ the things). Any downstream improvements would help upstream servers/proxies.

Separating preload and push doesn't magically solve any of the above problems. Whatever client's preload today they'd just replicate once over into the push relation -- yay duplicate values; giving the client a separate relation doesn't magically help them figure out what they want to push; if resource is not pushed you'd probably want the client to preload, at which point you're back to square one.

---

I think we also hijacked this thread, so to answer the question with respect to original thread:
- I think 'critical' (https://github.com/w3c/preload/issues/66#issuecomment-234687178) still makes sense.
- I also still think something like https://github.com/w3c/preload/issues/66#issuecomment-224339643 is not entirely crazy either.

Let me know how you guys want to proceed here.

---

_Update, some links for posterity..._
- https://icing.github.io/mod_h2/httpws-2016.html
- https://lukasa.co.uk/2016/07/HTTP_Workshop_and_Python/

**Comment by mnot** [comment] 2016-08-02 10:22
+1 to `critical`, although we might want to consider a different name (to avoid further intimation that this is a requirement, not a hint). E.g., maybe `interleave`?

**Comment by igrigorik** [comment] 2016-08-02 15:56
`critical` is nice in that it offers a connection to "critical path" ~~ this annotation specifies that the resource is on the critical application path, the server should prioritize this accordingly. 

`interleave` seems to assume that you are.. interleaving, which is not necessarily the case. If we follow @yoavweiss favorite use case of having the edge push critical resources while waiting for the origin to respond, you're probably not interleaving much of anything.

Other suggestions?

**Comment by mnot** [comment] 2016-08-02 15:59
That makes sense. I think `critical` is fine, as long as the description is clear.

**Comment by icing** [comment] 2016-11-14 12:27
`critical` is implemented in [mod_h2 v1.8.0](https://github.com/icing/mod_h2/releases/tag/v1.8.0) and will also be in the next Apache 2.4.24 release.

**Comment by addyosmani** [comment] 2017-07-28 20:50
It appears there was general support for the notion of `critical` on this thread and (correct me if wrong), `interleave` didn't get traction. Is there a next step forward here?

**Comment by yoavweiss** [comment] 2017-08-30 11:01
Closing as I think these hints could and should be addressed by a more general [resource priorities specification](https://github.com/WICG/resource-priorities). I believe this use case is described [there](https://github.com/WICG/resource-priorities#communicate-resource-importance-to-the-browser).

If you feel this use-case should be spelled out further there, PRs welcome :)

**Comment by mnot** [comment] 2017-08-30 23:42
It's not clear that RP is going to be available to intermediaries (where this information is most obviously consumed), and it's probably going to take a while. Why fate-share?

**Comment by yoavweiss** [comment] 2017-08-31 04:02
> It's not clear that RP is going to be available to intermediaries (where this information is most obviously consumed)

I think it should be. We are discussing a markup version that will most likely impact `<link>` and hence `Link:`.



> Why fate-share?

Because it's essentially solving the same problem, I don't see why we'd need something preload specific in the long run.

**Comment by mnot** [comment] 2017-08-31 04:14
🤷‍♂️ It seemed like we had emerging consensus here. Seems odd to shut it down for something that's just vigorous hand-waving at this point.

**Comment by yoavweiss** [comment] 2017-08-31 05:00
I think it boils down to the push use case vs. the preload use case (again).

For the "preload as a push signal" use case, we had consensus here that `critical` is good enough.
For actual preload, `critical` is meaningless, and what we really need is a way to mark resources as "non-critical" (so that they won't contend with critical resources), as well as a way to define deferring or dependencies of preloaded resources (e.g. I want to use LRP to speed up the discovery of subresources without them contending for bandwidth with more critical resources).

I'm [at peace](https://github.com/w3c/preload/issues/99#issuecomment-325955599) with using `rel=preload` as a push signal (as in "I don't like it, but :man_shrugging:"). At the same time, I don't think we should continue polluting `preload` with attributes which sole purpose is better handling of that use case, especially not while discussing a more generic solution for a very similar use case.

I agree that Resource Priorities is at a very early stage (I think you were generous with "vigorous hand-waving", we're still at the "gathering all the use cases" phase). At the same time, this issue has been laying here without any spec action for over a year. In any case, re-opening this to continue the discussion.

**Comment by mnot** [comment] 2017-08-31 05:19
I wonder if `critical` is interesting enough to PUSH folks to entice them to use something other than `preload`.  I suspect not, since it's already deployed in lots of places that are not terribly well-coordinated.

OTOH browser handling of `preload` is currently just in Chrome (and other blink-based browsers); it' s not hitting Safari and Firefox until their next release. If we really want to separate these semantics (and I'm not sure that's widely agreed to yet?), the path of least resistance might be to change them, not the push use cases. 

Any separation at this point is going to be disruptive, of course. I don't know how much content relies on browser handling of preload.

Just an observation.

**Comment by yoavweiss** [comment] 2017-08-31 06:17
> OTOH browser handling of preload is currently just in Chrome (and other blink-based browsers); it' s not hitting Safari and Firefox until their next release.

It's true that it's currently only *shipped* in Chromium, but it's fully implemented in both Safari Tech Preview as well as Firefox 57.

 

> If we really want to separate these semantics (and I'm not sure that's widely agreed to yet?), the path of least resistance might be to change them, not the push use cases.

I'm not sure what you're suggesting, but at least at the moment the "push semantics" part of preload has no impact on the way browsers process preload.



> I don't know how much content relies on browser handling of preload.

[0.7% of pages that Chrome sees](https://www.chromestatus.com/metrics/feature/popularity#LinkRelPreload) contain link rel preload.

**Comment by mnot** [comment] 2017-08-31 06:26
Ah, thx. Just thinking out loud.

**Comment by yoavweiss** [comment] 2018-08-20 08:07
@mnot https://github.com/WICG/priority-hints (the current incarnation of resource priorities) has made some progress, and is implemented in Chromium behind a flag, and can easily be extended to cover Link headers as well. I believe we can close this as it covers the use-case you want to tackle. Any objections?

**Comment by mnot** [comment] 2018-10-08 05:12
It seems like `critical` has multiple implementations and is seeing some level of interop, so I suspect it may not be that easy to transition over. @kazuho / @icing?

The pragmatic thing to do might be to specify `critical` somewhere really briefly to facilitate its registration; if priority hints does get good traction, the implementations can still do the right thing.

**Comment by icing** [comment] 2018-10-08 07:34
It will be fairly easy to add support for _parsing_ ```importance=critical``` and make it equivalent to the standalone ```critical``` attribute. This is all undiscovered country and may need multiple paths to explore.

However, when generating ```Link```(sry. ```link```) headers, should I now add both? That lacks elegance. Please advise.

**Comment by yoavweiss** [comment] 2018-10-08 07:51
> It seems like `critical` has multiple implementations

To be clear, you're talking about server implementations, right? AFAIK, there are no browser implementations for this. (and I suspect browser implementers will not be excited to implement two different attributes with similar impact)

> However, when generating `Link`(sry. `link`) headers, should I now add both?

What's the use case for adding them at all? (I thought Apache is supposed to be the end-consumer of preload-as-a-push-hint)

**Comment by icing** [comment] 2018-10-08 08:00
> What's the use case for adding them at all? (I thought Apache is supposed to be the end-consumer of preload-as-a-push-hint)

"It's servers all the way down."

The server can be at the edge, but it can also be proxied. I recommend that the edge server does PUSH, but the backends only send 103 with Link headers. In such a scenario, forwarding ```critical``` information is useful.

So, the compromise would be to _parse_ the ```priority=critical``` as well and _generate_ only the ```critical``` attribute. I guess?

**Comment by yoavweiss** [comment] 2018-10-08 08:08
I understand the forwarding use-case (so if current proxy doesn't interpret preload as a push hint, it relays it for the next one down the line (although that can have undesired side-effects in the preload hint reaches the browser when it wasn't intended for it)).

I have less-solid understanding of the generation use-case. How can Apache know which resources are critical and which aren't? Config?
In any case, I think you'd want to make sure your stack uses the standard attributes (which right now seem to be converging on `importance=high`) rather than the non-standard `critical`.

**Comment by icing** [comment] 2018-10-08 08:12
> (although that can have undesired side-effects in the preload hint reaches the browser when it wasn't intended for it))

A link header is part of the resource meta and not stripped by my implementation. So, it will reach the browser. And the browser needs to deal with it.

> I have less-solid understanding of the generation use-case. How can Apache know which resources are critical and which aren't? Config?

Yes, config.

> In any case, I think you'd want to make sure your stack uses the standard attributes (which right now seem to be converging on importance=high) rather than the non-standard critical.

That was the question. If ```importance=XXX``` is the way forward, I can change accordingly.

**Comment by noamr** [comment] 2022-03-28 06:07
Doesn't this get solved by [priority hints](https://web.dev/priority-hints/)?

**Comment by yoavweiss** [comment] 2022-03-28 06:17
In a way, but I'm worried about confusing priority-hints semantics with those of Server Push. 
Generally, I think there's at least some consensus that reusing `preload` as a hint to trigger Server Push resulted in a sub-optimal outcome, so I would generally prefer if we were to discourage this practice going forward.

@mnot @icing @kazuho @pmeenan  - what do y'all think?

**Comment by mnot** [comment] 2022-03-28 06:19
I think this is Overcome By Events.

**Comment by yoavweiss** [comment] 2022-03-28 06:23
@mnot - does that mean that from your perspective, we can close this?

**Comment by mnot** [comment] 2022-03-28 06:39
Yep.

**Comment by yoavweiss** [comment] 2022-03-28 06:51
In that case, I'm closing this. If anyone feels we should reopen, feel free to comment further!

**Closed as completed by yoavweiss** 2022-03-28 06:51 UTC
Labels: whiteboard, non-blocking
